name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install Go tooling
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: Get dependencies
      run: |
        if ! command -v make &> /dev/null ; then
          echo "Installing make"
          apt-get update
          apt-get install -y make
        fi
        if ! command -v git &> /dev/null ; then
          echo "Installing git"
          apt-get update
          apt-get install -y git
        fi
        go get -v -t -d ./...

    - name: Build
      run: make linux

    - name: Test
      run: make test bench
      env:
        CGO_ENABLED: 0

    - name: Coverage
      run: make coverage
      env:
        CGO_ENABLED: 0

    - name: Build Docker Image
      run: |
        make docker-image
      env:
        CGO_ENABLED: 0

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/halplatform/waver:${{ github.sha }}'
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
