name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install Go tooling
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
